### ISSUE TITLE
MLTOOLS not able to run

### ISSUE THREAD

**Issue by spbhasker** [DigitalGlobe/mltools#1]
Hi .. After installation of Mltools Stuck @ crowdsourcing.py
I sense this connects to Tomnod Database using Psycopg2 
can someone help me on this . Not moving forward from here

****In [8]: import mltools
  File "C:\Anaconda3\lib\site-packages\mltools\crowdsourcing.py", line 43
    except psycopg2.ProgrammingError, e:
                                    ^
SyntaxError: invalid syntax****

**Comment by kstamatiou** [comment]
@spbhasker: I can't replicate your issue. I am guessing you're using Python 3?
Switch to Python 2.7

**Comment by spbhasker** [comment]
Dear Kostas

I was finally able to set it up on 2.7

However the process is very very slow .. It took me 60 hours to run the
Detection of Swimming Pools

Any tips to run it more quicker ????

Regards

**Comment by kstamatiou** [comment]
Hi @spbhasker.

I am guessing you are running on a CPU? It should not take that long on a
GPU.

**Comment by Yashwanthv21** [comment]
@kostasthebarbarian  @spbhasker  Did you publish the trained model weights somewhere ?. Is there a way to access it ?
